# docker run --cap-add SYS_PTRACE -e 'ACCEPT_EULA=1' -e 'MSSQL_SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 --name azuresqledge -d mcr.microsoft.com/azure-sql-edge

services:
  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
    #container_name: "ef-core-samples"
    # NOTE: can't use azure-sql-edge as it doesn't support .NET CLR.
    image: mcr.microsoft.com/mssql/server
    ports:
      # {{exposed}}:{{internal}} - you'll need to contain the exposed ports if you have more than one DB server running at a time
      - 1433:1433
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P yourStrong(!)Password -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s    
